server:
  port: '8085'
logging:
  level:
    org:
      springframework:
        web: TRACE
        cloud:
          gateway: TRACE
    web: TRACE
skill-service:
  api:
    uri: http://localhost:8082/
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: GET, POST

user-service:
  api:
    uri: http://localhost:8081/
user-skill-combiner:
  api:
    uri: http://localhost:8083/
mongo-service:
  api:
    uri: http://localhost:8086/
management:
  endpoint:
    web:
      exposure:
        includes: '"*'''
